from __future__ import annotations
from abc import ABC, abstractmethod
from app.models.project import ProjectCreate, ProjectResponse
from app.models.review import ReviewCreate, ReviewDetailResponse, ReviewResponse
from app.models.finding import FindingResponse

class ReviewRepository(ABC):
    @abstractmethod
    async def create_project(self, data: ProjectCreate) -> ProjectResponse: ...
    @abstractmethod
    async def get_project(self, project_id: str) -> ProjectResponse | None: ...
    @abstractmethod
    async def get_project_by_name(self, name: str) -> ProjectResponse | None: ...
    @abstractmethod
    async def list_projects(self) -> list[ProjectResponse]: ...
    @abstractmethod
    async def create_review(self, project_id: str, data: ReviewCreate) -> ReviewDetailResponse: ...
    @abstractmethod
    async def get_review(self, review_id: str) -> ReviewDetailResponse | None: ...
    @abstractmethod
    async def list_reviews(self, project_id: str) -> list[ReviewResponse]: ...
    @abstractmethod
    async def update_finding_status(self, finding_id: str, status: str) -> FindingResponse | None: ...
